site_name: Perifural 文档
site_url: https://docs.perifural.com
theme:
  name: material
  language: zh
  palette:
    primary: red
    accent: deep orange
extra:
  generator: false
copyright: 版权所有 &copy; 2025 普瑞福嵌入式系统